### ISSUE TITLE
How to set the  original audio (without effect) by default when opening the first time?

### ISSUE THREAD

**Issue by aahedi** [urtzurd/html-audio#5]
Good project I like.

How to set the original audio (without effect) by default when opening the first time?
and How to use only pitch effect without ratio and grain like [https://aahedi.github.io/data/PitchShifter/](https://aahedi.github.io/data/PitchShifter/)?

**Comment by urtzurd** [comment]
Hi!

The project always processes the audio through the algorithm, so currently there's no way to listen to the original unaffected signal. One easy way would be to add an option to disable the window function (currently Hann window is applied) or just use a rectangular window instead, that way with a ratio of 1 and no overlap, you could listen to the original audio.

The other project also has a ratio control in form of pitch percentage. I'm not sure what pitch shifting method the other project is using, but it might be using a frequency domain algorithm instead and not exposing whatever FFT window size and overlapping it's using, so other implementations will also have similar parameters.

Cheers.

**Comment by aahedi** [comment]
How to disable hannwindow so as not to overlap 2 sounds. So only 1 sound?

**Comment by urtzurd** [comment]
You can modify the function to generate a rectangular window changing https://github.com/urtzurd/html-audio/blob/gh-pages/static/js/pitch-shifter.js#L30 to:

```js
window[i] = 1;
```
Then set the overlap ratio slider to 0.
